AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Smart Reminder Service

Globals:
  Function:
    Timeout: 20
    Runtime: java17
    MemorySize: 512

Resources:
  ReminderSetupFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: com.company.service.ReminderSetupFunction::handleRequest
      Events:
        ApiEndpoint:
          Type: Api
          Properties:
            Path: /subscribe
            Method: post
            RestApiId: !Ref SmartReminderAPI
      Environment:
        Variables:
          TABLE_NAME: !Ref UserReminderInfo
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserReminderInfo

  SendReminderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: com.company.service.SendReminderFunction::handleRequest
      Events:
        DailySchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 * * * ? *)  # Every hour
      Environment:
        Variables:
          TABLE_NAME: !Ref UserReminderInfo
          SENDER_EMAIL: "manik39201@ikanteri.com"
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref UserReminderInfo
        - Statement:
            - Effect: Allow
              Action:
                - ses:SendEmail
                - ses:SendRawEmail
              Resource: "*"

  UserReminderInfo:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: email
        Type: String
      TableName: user_reminder_info

  SmartReminderAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: SmartReminderApi
      StageName: Prod
